/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPlanRouteImport } from './routes/api/plan'
import { Route as ApiMcpCourseRouteImport } from './routes/api/mcp-course'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlanRoute = ApiPlanRouteImport.update({
  id: '/api/plan',
  path: '/api/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpCourseRoute = ApiMcpCourseRouteImport.update({
  id: '/api/mcp-course',
  path: '/api/mcp-course',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/mcp-course': typeof ApiMcpCourseRoute
  '/api/plan': typeof ApiPlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/mcp-course': typeof ApiMcpCourseRoute
  '/api/plan': typeof ApiPlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/mcp-course': typeof ApiMcpCourseRoute
  '/api/plan': typeof ApiPlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/mcp-course' | '/api/plan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/mcp-course' | '/api/plan'
  id: '__root__' | '/' | '/api/mcp-course' | '/api/plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMcpCourseRoute: typeof ApiMcpCourseRoute
  ApiPlanRoute: typeof ApiPlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plan': {
      id: '/api/plan'
      path: '/api/plan'
      fullPath: '/api/plan'
      preLoaderRoute: typeof ApiPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp-course': {
      id: '/api/mcp-course'
      path: '/api/mcp-course'
      fullPath: '/api/mcp-course'
      preLoaderRoute: typeof ApiMcpCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMcpCourseRoute: ApiMcpCourseRoute,
  ApiPlanRoute: ApiPlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
